Fix for Issue #475
go-mgo/mgo pull request #476
Opened 2017-08-02 19:32 UTC by mapete94

[https://github.com/go-mgo/mgo/issues/475](url)

2017-08-03 09:28 UTC, niemeyer requested changes
Thanks for the change. Some minor requests below, and a  test for this would be good as well.

2017-08-03 09:28 UTC, niemeyer commented on session.go
>  		vi, ok := realKey[i].Value.(int)
This may be included in the type switch as well.

2017-08-03 09:28 UTC, niemeyer commented on session.go
> +				panic("Got unknown index key type for field " + field)
We pretty much never want to panic on bad data. The driver and the code is not at fault when the data is bogus.

2017-08-04 18:34 UTC, mapete94 commented
I made the requested changes. I did not add a test. I didn't see a way to create a 64bit int for your index type within the documentation. I may have missed it in the documentation, but if there is a way and I'm missing it I can write one.

2017-08-04 18:49 UTC, mapete94 commented on session.go
>  		vi, ok := realKey[i].Value.(int)
It's been incorporated into the case statement.

2017-08-04 18:49 UTC, mapete94 commented on session.go
> +				panic("Got unknown index key type for field " + field)
I've removed it, but there is a similar panic right below it that was the reason I included it.

2017-08-07 12:35 UTC, merged